# NPM Publish is the name for this action
name: build and publish

# This action will trigger on every release get created
on:
    workflow_dispatch:
    create:
        tag: [created]

# Job will run on a ubuntu instance
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout package repo
              uses: actions/checkout@v2
              with:
                  persist-credentials: false
            - name: setup node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  check-latest: true
                  registry-url: 'https://registry.npmjs.org'
              run: npm config set scope "@mattermost"
            - name: install dependencies
              run: npm install
            - name: build compass-icons
              working-directory: ./node_modules/@mattermost/compass-icons
              run: |
                  npm install
                  npm run build
            - name: build component library
              run: npm run build
            - name: publish to npm
              working-directory: ./lib
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
