# NPM Publish is the name for this action
name: npm publish

# This action will trigger on every release get created
on:
    create:
        tag: [created]

# Job will run on a ubuntu instance
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  persist-credentials: false
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  check-latest: true
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@mattermost'
            - name: Install
              run: npm install
            - name: Build Icons
              working-directory: ./node_modules/@mattermost/compass-icons
              run: |
                  npm install
                  npm run build
            - name: Build Component Library
              run: npm run build
            - name: checking npm configs
              run: npm config ls -l
            - name: Publish to npm
              working-directory: ./lib
              run: npm publish --access public
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
